language: python

python:
    - "3.6"

install:
    - pip install scipy
    - pip install numpy
    - pip install hypothesis
    - pip install matplotlib
    - pip install codecov pytest-cov                                           

script:
    - py.test -s -v tests/test_regression.py
    - py.test -s -v tests/test_hypothesis.py
                                                   
    - py.test --cov=./ --cov-report xml:cov.xml tests                          

after_success:                                                                 
    -  codecov --file cov.xml 
